-- AGGREGATE TOPPER (1,2,3 POSITIONS)
-- RULES:
-- MARKS > 60% IN EACH SUBJECT
-- IF TWO STUDENTS HAVE SAME MARKS THEN SAME POSITION 
SELECT NAME as "Name",MARKS1 + MARKS2 + MARKS3 + MARKS4 as 'Total Marks', RANK() OVER (ORDER BY MARKS1+mArks2+MARKS3+MARKS4 DESC) AS "Rank" FROM MARKS WHERE MARKS1 > (45 * 0.6) AND MARKS2 > (65 * 0.6) AND MARKS3 > (65 * 0.6) AND MARKS4 > (65 * 0.6) LIMIT 3 ;