-- SUBJECT 2 TOPPER (1,2,3 POSITIONS)
-- RULES:
-- MARKS > 60% IN EACH SUBJECT
-- IF TWO STUDENTS HAVE SAME MARKS, THEN COMPARE BY AGGREGATE OF ALL SUBJECTS, IF AGGREGATE SAME THEN SAME POSITION
SELECT name as "Name",marks2 as 'Subject 2', RANK() OVER (ORDER BY marks2 DESC,marks1+marks2+marks3+marks4 DESC) AS "Rank" FROM marks WHERE marks1 > (45 * 0.6) AND marks2 > (65 * 0.6) AND marks3 > (65 * 0.6) AND marks4 > (65 * 0.6) LIMIT 3 ;