-- CREATE VIEW view_name AS SELECT column1, column2 FROM table_name WHERE condition
CREATE VIEW HIGH_SCORERS AS SELECT NAME, (MARKS1 + MARKS2 + MARKS3 + MARKS4) AS TOTAL FROM MARKS WHERE ( MARKS1 + MARKS2 + MARKS3 + MARKS4 ) > 160;

SELECT * FROM HIGH_SCORERS ORDER BY TOTAL;
